
public interface ComponentSize {
	int FRAME_PANEL_WIDTH = 800;
	int FRAME_PANEL_HEIGHT = 600;
	
	int BUTTON_WIDTH = 100;
	int BUTTON_HEIGHT = 50;
	
	int MESSAGE_WIDTH = 600;
	int MESSAGE_HEIGHT = 280;
	
	int SHOW_RECIPE_LABEL_WIDTH = 350;
	int SHOW_RECIPE_LABEL_HEIGHT = 350;
	
	
	int NOW_LABEL_VALUES_WIDTH = 250;
	int NOW_LABEL_VALUES_HEIGHT = 50;
	
	int ORDER_PRINT_LABEL_WIDTH = 250;
	int ORDER_PRINT_LABEL_HEIGTH = 50;
	
	
}
